version: '3.8'

services:
  detection-api:
    image: szabobeno/felholabor-nagyhf:detection-api-${IMAGE_TAG}
    ports:
      - "4000:4000"
    networks:
      - labor-network
    depends_on:
      - database
    environment:
      PYTHON_HOST: 'detection-api'
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: 'labor_hf'
      MYSQL_USER: 'benedek'
      MYSQL_PASSWORD: 'benedek'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    networks:
      - labor-network
    volumes:
      - mysql_data:/var/lib/mysql
  backend-server:
    image: szabobeno/felholabor-nagyhf:backend-server-${IMAGE_TAG}
    ports:
      - "5000:5000"
    networks:
      - labor-network
    depends_on:
      - database
    environment:
      DETECTION_HOST: 'detection-api'
      DB_HOST: 'database'
  frontend:
    image: szabobeno/felholabor-nagyhf:frontend-${IMAGE_TAG}
    ports:
      - "8080:80"
    networks:
      - labor-network
    environment:
      BACKEND_HOST: 'backend-server'
networks:
  labor-network:
    driver: bridge
volumes:
  mysql_data:

# trigger a run