version: '3.8'

services:
  detection-api:
    image: szabobeno/felholabor-nagyhf:detection-api-${IMAGE_TAG}
    ports:
      - "4000:4000"
    networks:
      - labor-network
    depends_on:
      - database
    environment:
      PYTHON_HOST: 'detection-api'
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
    ports:
      - "3306:3306"
    networks:
      - labor-network
    volumes:
      - mysql_data:/var/lib/mysql
  labor-mq:
    image: szabobeno/felholabor-nagyhf:labor-mq-${IMAGE_TAG}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - labor-network
  backend-server:
    image: szabobeno/felholabor-nagyhf:backend-server-${IMAGE_TAG}
    ports:
      - "5000:5000"
    networks:
      - labor-network
    depends_on:
      - database
      - detection-api
      - labor-mq
    environment:
      DETECTION_HOST: 'detection-api'
      DB_HOST: 'database'
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      MQ_HOST: 'labor-mq'
  frontend:
    image: szabobeno/felholabor-nagyhf:frontend-${IMAGE_TAG}
    ports:
      - "8080:80"
    networks:
      - labor-network
    environment:
      BACKEND_HOST: 'http://127.0.0.1:63434/'
networks:
  labor-network:
    driver: bridge
volumes:
  mysql_data: