# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: mq
        image: szabobeno/felholabor-nagyhf:labor-mq-{{ .Values.IMAGE_TAG }}
        ports:
        - containerPort: {{ .Values.mqPort }}
      - name: db
        image: szabobeno/felholabor-nagyhf:db-{{ .Values.IMAGE_TAG }}
        ports:
        - containerPort: {{ .Values.dbPort }}
      - name: detection-api
        image: szabobeno/felholabor-nagyhf:detection-api-{{ .Values.IMAGE_TAG }}
        ports:
        - containerPort: {{ .Values.detectionApiPort }}
      - name: frontend
        image: szabobeno/felholabor-nagyhf:frontend-{{ .Values.IMAGE_TAG }}
        ports:
        - containerPort: {{ .Values.frontendPort}}
        env:
          - name: BACKEND_HOST
            value: "backend"
          - name: BACKEND_PORT
            value: "{{ .Values.backendPort }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: szabobeno/felholabor-nagyhf:backend-server-{{ .Values.IMAGE_TAG }}
        ports:
        - containerPort: {{ .Values.backendPort }}
        env:
          - name: DB_HOST
            value: "frontend:{{ .Values.dbPort }}"
          - name: MQ_HOST
            value: "frontend:{{ .Values.mqPort }}"
          - name: DETECTION_HOST
            value: "frontend:{{ .Values.detectionApiPort }}"