# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: mq
        image: szabobeno/felholabor-nagyhf:labor-mq-{{ .Values.IMAGE_TAG }}
        ports:
        - containerPort: {{ .Values.mqPort }}
      - name: detection-api
        image: szabobeno/felholabor-nagyhf:detection-api-{{ .Values.IMAGE_TAG }}
        ports:
        - containerPort: {{ .Values.detectionApiPort }}
      - name: backend
        image: szabobeno/felholabor-nagyhf:backend-server-{{ .Values.IMAGE_TAG }}
        ports:
        - containerPort: {{ .Values.backendPort }}
      - name: frontend
        image: szabobeno/felholabor-nagyhf:frontend-{{ .Values.IMAGE_TAG }}
        ports:
        - containerPort: {{ .Values.frontendPort}}