apiVersion: v1
kind: Service
metadata:
  name: felho-labor-nagyhf
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: felho-labor-nagyhf