apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: argo-hf-ns
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: frontend