apiVersion: v1
kind: Service
metadata:
  name: felho-labor-nagyhf
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: https
  selector:
    app: felho-labor-nagyhf