apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: argo-hf-ns
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: backend
    - port: 4000
      targetPort: 4000
      protocol: TCP 
      name: detection-api
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: mq
  selector:
    app: frontend