version: '3.8'

services:
  detection-api:
    image: detection
    ports:
      - "4000:4000"
    networks:
      - labor-network
    depends_on:
      - database
    environment:
      PYTHON_HOST: 'localhost'
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: 'labor_hf'
      MYSQL_USER: 'benedek'
      MYSQL_PASSWORD: 'benedek'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    networks:
      - labor-network
    volumes:
      - mysql_data:/var/lib/mysql
  labor-mq:
    image: labor-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - labor-network
    depends_on:
      - database
  backend-server:
    image: backend
    ports:
      - "5000:5000"
    networks:
      - labor-network
    depends_on:
      - database
      - detection-api
      - labor-mq
    environment:
      DETECTION_HOST: 'detection-api'
      DB_HOST: 'database'
      DB_USER: 'benedek'
      DB_PASSWORD: 'benedek'
      DB_NAME: 'labor_hf'
      MQ_HOST: 'labor-mq'
  frontend:
    image: labor-frontend
    ports:
      - "8080:80"
    networks:
      - labor-network
    environment:
      BACKEND_HOST: 'backend-server'
      BACKEND_PORT: '5000'
networks:
  labor-network:
    driver: bridge
volumes:
  mysql_data: