# Use the official MySQL image
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=labor-db
ENV MYSQL_USER=benedek
ENV MYSQL_PASSWORD=benedek

EXPOSE 3306