name: frontend
replicas: 2
IMAGE_TAG: 36f7da7b96b95da351aa1e0da4b2faed6e79fb8b
test: test
frontendPort: 80
frontendNodePort: 30081
backendPort: 5000
backendNodePort: 30050
detectionApiPort: 4000
detectionApiNodePort: 30040
mqPort: 5672
mqNodePort: 30672
dbPort: 3306
dbNodePort: 30306