name: Test, build and release
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: TODO Add tests
        run: echo TODO Add tests
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Dir check
        run: ls -la ./detection

      - name: Build and push detection-api image
        uses: docker/build-push-action@v2
        with:
          context: ./detection
          file: Dockerfile
          push: true
          tags: |
            szabobeno/felholabor-nagyhf:latest
            szabobeno/felholabor-nagyhf:detection-api-${{ github.sha }}

      - name: Build and push backend-server image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: Dockerfile
          push: true
          tags: |
            szabobeno/felholabor-nagyhf:latest
            szabobeno/felholabor-nagyhf:backend-server-${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: Dockerfile
          push: true
          tags: |
            szabobeno/felholabor-nagyhf:latest
            szabobeno/felholabor-nagyhf:frontend-${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag env var
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d --build